name: Genetics_Project_Collaborative
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  #- blast>=2.7.1
  #- cd-hit>=4.8.1
  #- ipycytoscape
  - matplotlib
  - clustalo
  - numpy>=1.18.5
  - py3Dmol
  - pymol
